---
extends:
  - "airbnb-base"
  - "prettier"
plugins:
  - "@typescript-eslint"
  - "prettier"
parser: "@typescript-eslint/parser"
rules:
  semi: [2, never]
  import/no-unresolved: 0
  no-restricted-globals: [0, []]
  import/extensions: [0, "never"]
  prettier/prettier: "error"
env:
  browser: true
